### ISSUE TITLE
celsius values not exported

### ISSUE THREAD

**Issue by jamessanford** [jamessanford/currentcost_exporter#2]
The exporter looks for a `tmprF` tag, but units in most of the world use a `tmpr` tag to export celsius.  The exporter should look for and export that tag as well.

**Comment by kaihendry** [comment]
<img src=http://s.natalian.org/2016-09-09/1473435954_2548x1380.png>

Ah yes, my unit outputs Celsius with `tmpr`.

`<msg><src>CC128-v1.29</src><dsb>00363</dsb><time>02:56:56</time><tmpr>31.0</tmpr><sensor>0</sensor><id>00077</id><type>1</type><ch1><watts>00616</watts></ch1></msg>`
